<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4019.2">
  <POU Name="MAIN" Id="{f9a624a7-3b5f-4807-8bd7-72971c0fcf58}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbMyPizzaOven1 : FB_PIZZA_OVEN;
	
	bLoadPizza   : BOOL;
	bRemovePizza : BOOL;	
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[

fbMyPizzaOven1(bLoadPizza:= bLoadPizza, bRemovePizza:=bRemovePizza);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>